### ISSUE TITLE
Strange offset of icons undex lxpanel-gtk3

### ISSUE THREAD

**Issue by FredericGuilbault** [lxde/lxpanel#23]
Hi, idk if you  support lxpanel-gtk3. id so.

I'm using the binary compiled here 
https://launchpad.net/~mati75/+archive/ubuntu/lubuntu-testing/
And I have this strange offset in the taskbar plugin

![image](https://user-images.githubusercontent.com/37122999/102036285-7015e480-3d90-11eb-935c-743ded33a66c.png)

It appends independently of the theme used. 

That sound like a padding-left problem of the box.  I thought that I could fix it inside a gtkrc file. But with gtk3, lxpanel seems to ignore the file I put in  `~/.config/lxpanel/$PROFILE/gtkrc.`  

What would be the correct way to do this with gtk3 ?

**Comment by ib** [comment]
@FredericGuilbault, could you please provide a screenshot of the panel itself showing the strange icon offsets?

**Comment by ib** [comment]
Fixed.
