### ISSUE TITLE
Weather plugin does not use translated strings initially, only after visiting Settings dialog

### ISSUE THREAD

**Issue by jose1711** [lxde/lxpanel#24]
Demonstration of the problem on Raspberry Pi

https://user-images.githubusercontent.com/1406222/103641133-8b1fe280-4f51-11eb-903e-d49b90a859c1.mp4

**Comment by ib** [comment]
I don't have access to a Raspberry Pi, but I can't reproduce on a PC.

What distribution and version does the bug occur on?

**Comment by ib** [comment]
What is your locale?

**Comment by jose1711** [comment]
> I don't have access to a Raspberry Pi, but I can't reproduce on a PC.
> 
> What distribution and version does the bug occur on?

This was quite a long time ago. I believe it was freshly installed Raspbian, locale set to `sk_SK`.

**Comment by ib** [comment]
So, does the bug still exist?

**Comment by jose1711** [comment]
As I am also unable to reproduce, we can close it.
