### ISSUE TITLE
NetSpeed - NetLoad plugin for lxpanel

### ISSUE THREAD

**Issue by Zen997** [lxde/lxpanel#36]
This is a Feature Request and not an issue.
The lxpanel is great, but it is missing a "NetSpeed" plugin that is available in gnome-panel as shell extension, mate-panel as an applet and xfce4-panel as "xfce4-netload-plugin".
I'd like to ask any programmer, who is interested to create new or modify/reprogram an existing applet/plugin. Here are some existing projects for xfce4, mate and gnome panels:

https://github.com/search?q=xfce4-netload-plugin

https://github.com/search?q=mate-netspeed

https://github.com/search?q=gnome-netspeed

Thank you very much.

**Comment by Denzy7** [comment]
Hey. I happen to have just the [plugin](https://github.com/Denzy7/lxNetSpeedMonitor)

**Comment by Zen997** [comment]
Hello and thank you. I have tried to install the plugin (my OS is Debian 11 with LXDE), but got a bunch of errors:
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
cmake --build build
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:  && 
 I am not a programmer, so I couldn't resolve the errors. Any advice? Thanks.

**Comment by Denzy7** [comment]
Hi  
Ensure you have installed build dependencies.  
Try running `make --v` if not found install:  
`sudo apt install build-essential pkg-config`  
Check lxpanel with pkg-config:  
`pkg-config --cflags lxpanel`  
Should return a whole lot of directories that start with -I  
Should now build!

**Comment by Zen997** [comment]
Hello Dennis and thank you so much!
I truly appreciate your help and timely response. I have been asking this question on multiple Linux forums, but you are the only one who responded with a usable answer. I am one of those who prefers tried and true instead of new and unknown, functionality over eye candy, minimalist system with only absolutely necessary packages installed over average user oriented system. For the reasons above LXDE is my only preferred DE and Debian, Devuan and Star are my preferred distros. Xfce and MATE are also OK, but I always come back to LXDE. I love lxpanel and the only missing plugin in my opinion is the NetSpeed. I will try your solution and comment with the results. Thanks again.

**Comment by Denzy7** [comment]
Glad to see you are interested! 
I [updated the build instructions](https://github.com/Denzy7/lxNetSpeedMonitor) too

**Comment by Zen997** [comment]
Hello Dennis,
With your help I managed to build and install the NetSpeedMonitor plugin. I was missing some programming and development related packages on my system. After installing build-essential and lxpanel-dev packages with all dependencies and resolving the error below, I finally got the actual plugin - "netspeedmonitor.so", which I copied to /usr/lib/x86_64-linux-gnu/lxpanel/plugins. After reboot and adding the NetSpeedMonitor to lxpanel, everything is working perfectly (screenshot attached). 

--   No package 'lxpanel' found
Package lxpanel was not found in the pkg-config search path.
Perhaps you should add the directory containing `lxpanel.pc'
to the PKG_CONFIG_PATH environment variable

Thank you so much for your help!
![NetSpeedMonitor](https://user-images.githubusercontent.com/93111284/160943104-c7dbcebb-51de-4008-b8c2-bd4044ca5359.png)
![LXDE-NetSpeed](https://user-images.githubusercontent.com/93111284/160943122-f1911d25-46b8-4fb8-9a57-23fe96ba5085.jpg)

**Comment by Denzy7** [comment]
Awesome. You can now close this issue

**Comment by Zen997** [comment]
Hello Dennis and thank you again for helping me with the NetSpeedMonitor
plugin for lxpanel in LXDE 3 years ago.
Your plugin works absolutely perfect on Debian 11 and 12 as well as on
Devuan 4 and 5. With the new Debian 13 and Devuan 6, I am unable to add the
plugin to the lxpanel (it is not in the "Add / Remove Panel Items" list).
As with previous Debian releases the plugin "netspeedmonitor.so" is in the
/usr/lib/x86_64-linux-gnu/lxpanel/plugins  directory, but not in the "Add /
Remove Panel Items" list. If you have any solutions, please let me know.
Thank you very much.

Mike.

**Comment by Denzy7** [comment]
Hi @Zen997. I'm really happy to hear it still working! It's been years since I've used LXDE, I'll have a look at it this weekend and hopefully have an answer soon
