### ISSUE TITLE
Volume plugin does not work properly when built with gtk+3

### ISSUE THREAD

**Issue by nsalguero** [lxde/lxpanel#45]
Hi,

When lxpanel is built with gtk+3, the volumealsa plugin has two issues:

1. Scrolling mouse wheel on the icon from lxpanel does nothing because of a missing `gtk_widget_add_events(p, GDK_SCROLL_MASK)`.
2. In the window of the plugin, scrolling mouse wheel only decreases the volume because the direction `GDK_SCROLL_SMOOTH` is not taken into account.

Best regards,

**Comment by ib** [comment]
See #46.
